"""OKF bundle construction for compression output.

Pure functions that turn a :class:`ceng.compress.CompressionBundle`
into a list of :class:`ceng.okf.Concept` instances ready for
:func:`ceng.okf.write_bundle`. Kept separate from the compression
pipeline so each piece is independently testable.
"""

from __future__ import annotations

from ceng.okf import (
    CENG_BUNDLE_INDEX,
    CENG_COMBINED_SUMMARY,
    CENG_LEAF_SUMMARY,
    RESERVED_INDEX,
    Concept,
    Frontmatter,
    now_iso,
)

# Import here to avoid a circular dependency: compress/__init__.py
# exports CompressionBundle; bundle.py imports it lazily.
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from ceng.compress import CompressionBundle


def build_bundle_concepts(
    bundle: "CompressionBundle",
    bundle_name: str,
    tokenizer=None,
    index_only: bool = False,
) -> list[Concept]:
    """Convert a :class:`CompressionBundle` into OKF concepts.

    Always emits at least one :data:`RESERVED_INDEX` concept. For
    bundles with leaves, also emits one leaf concept per leaf and a
    combined summary concept (only when there's more than one
    leaf — a single-leaf bundle's leaf IS the combined summary so
    emitting a copy would be wasted bytes).

    When ``index_only=True``, only the index plus the combined
    summary are emitted; the per-leaf concepts are *not*
    materialised. Callers that want them can use
    :func:`ceng.playbook.evolver.run` (or any future rendering
    pipeline) to render them on demand.
    """
    concepts: list[Concept] = []

    if bundle.leaves:
        leaf_links: list[str] = []
        for leaf in bundle.leaves:
            path = f"leaf-{leaf.index}.md"
            leaf_links.append(f"[{path}]({path})")
            if index_only:
                continue
            concepts.append(
                Concept(
                    frontmatter=Frontmatter(
                        type=CENG_LEAF_SUMMARY,
                        title=f"Leaf {leaf.index} summary",
                        description=_first_line(leaf.summary, 200),
                        tags=(
                            "ppa",
                            f"leaf-{leaf.index}",
                            "cache-hit" if leaf.cache_hit else "cache-miss",
                        ),
                        timestamp=now_iso(),
                    ),
                    body=_render_leaf_body(leaf),
                    path=path,
                )
            )

        if len(bundle.leaves) > 1:
            concepts.append(
                _combined_concept(bundle, leaf_links)
            )
            index_entries = [
                "- [Combined summary](combined.md)"
            ] + [f"- {link}" for link in leaf_links]
        else:
            index_entries = [f"- {link}" for link in leaf_links]
        concepts.append(_index_concept(bundle, bundle_name, index_entries))
    else:
        concepts.append(_noop_index_concept(bundle, bundle_name))

    return concepts


def _combined_concept(bundle: "CompressionBundle", leaf_links: list[str]) -> Concept:
    return Concept(
        frontmatter=Frontmatter(
            type=CENG_COMBINED_SUMMARY,
            title="compressed bundle combined summary",
            description=_first_line(bundle.combined_summary, 200),
            tags=("ppa", "combined"),
            timestamp=now_iso(),
        ),
        body=bundle.combined_summary
        + "\n\n## Cross-links\n\n"
        + "\n".join(f"- {link}" for link in leaf_links)
        + "\n",
        path="combined.md",
    )


def _index_concept(
    bundle: "CompressionBundle", bundle_name: str, entries: list[str]
) -> Concept:
    body = (
        f"# {bundle_name}\n\n"
        f"Bundle produced by `ceng.ppa_compress_to_okf`. "
        f"{bundle.leaf_count} leaves, "
        f"{bundle.cache_hits} cache hits, {bundle.cache_misses} misses.\n\n"
        f"## Sections\n\n"
        + "\n".join(entries)
        + "\n"
    )
    return Concept(
        frontmatter=Frontmatter(
            type=CENG_BUNDLE_INDEX,
            title=f"{bundle_name} index",
            description="Top-level OKF index generated by ceng",
            tags=("ppa", "bundle-index"),
            timestamp=now_iso(),
        ),
        body=body,
        path=RESERVED_INDEX,
    )


def _noop_index_concept(bundle: "CompressionBundle", bundle_name: str) -> Concept:
    return Concept(
        frontmatter=Frontmatter(
            type=CENG_BUNDLE_INDEX,
            title=f"{bundle_name} index",
            description="No compression was needed; original already fits the budget.",
            tags=("ppa", "bundle-index", "noop"),
            timestamp=now_iso(),
        ),
        body=(
            f"# {bundle_name}\n\n"
            f"Original message was {bundle.original_tokens} tokens, "
            f"under the budget of compressed output. No leaves generated.\n"
        ),
        path=RESERVED_INDEX,
    )


def _render_leaf_body(leaf) -> str:
    """Build the markdown body for a leaf concept."""
    return (
        f"## Summary\n\n"
        f"{leaf.summary}\n\n"
        f"## Original chunk\n\n"
        f"```\n{leaf.text}\n```\n"
    )


def _first_line(text: str, limit: int) -> str:
    if not text:
        return ""
    return text.splitlines()[0][:limit]
