"""Token usage and cost accounting."""

from __future__ import annotations

import dataclasses
from collections.abc import Mapping


@dataclasses.dataclass(frozen=True, slots=True)
class Usage:
    """Token usage of one or more backend calls.

    Attributes:
        prompt_tokens: Tokens sent to the model.
        completion_tokens: Tokens generated by the model.
    """

    prompt_tokens: int = 0
    completion_tokens: int = 0

    @property
    def total_tokens(self) -> int:
        """Returns prompt plus completion tokens."""
        return self.prompt_tokens + self.completion_tokens

    def __add__(self, other: Usage) -> Usage:
        return Usage(
            self.prompt_tokens + other.prompt_tokens,
            self.completion_tokens + other.completion_tokens,
        )


@dataclasses.dataclass(frozen=True, slots=True)
class Price:
    """Per-million-token prices in USD."""

    prompt_per_million: float
    completion_per_million: float


@dataclasses.dataclass(frozen=True, slots=True)
class PriceTable:
    """Maps model names to prices; unknown models cost zero.

    Attributes:
        prices: Model name to `Price`.
    """

    prices: Mapping[str, Price] = dataclasses.field(default_factory=dict)

    def cost(self, model: str, usage: Usage) -> float:
        """Returns the USD cost of `usage` on `model` (0.0 if unpriced)."""
        price = self.prices.get(model)
        if price is None:
            return 0.0
        return (
            usage.prompt_tokens * price.prompt_per_million
            + usage.completion_tokens * price.completion_per_million
        ) / 1_000_000
